name: Golang

on:
  workflow_dispatch: {}
  schedule:
    - cron: "30 1 * * *" # 1 AM UTC, 6 PM PST

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SHA
        id: sha
        run: echo "sha=$(/usr/bin/git log -1 --format='%H')" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Set Tags
        id: tags
        run: |
          echo "date_stamp=$(date +"%F")" >> $GITHUB_OUTPUT
          echo "week_stamp=$(date +"%Y-%U")" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: golang
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.REGISTRY }}${{ vars.IMAGE_PREFIX }}/golang:1.22-bullseye
            ${{ vars.REGISTRY }}${{ vars.IMAGE_PREFIX }}/golang:1.22-bullseye-${{ steps.tags.outputs.date_stamp}}
            ${{ vars.REGISTRY }}${{ vars.IMAGE_PREFIX }}/golang:1.22-bullseye-${{ steps.tags.outputs.week_stamp}}
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
