name: Toolkit

on:
  workflow_dispatch: {}
  schedule:
    - cron: "30 2 * * *" # 2:30AM UTC, 7:30PM PST

jobs:
  git:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  kaniko:
    runs-on: [ubuntu-22.04]
    needs: [git]
    container:
      image: gcr.io/kaniko-project/executor:v1.23.2-debug
    permissions:
      contents: read # read the repository
    steps:
      - name: AWS Credentials
        id: login-aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Defined at https://github.com/holos-run/holos-infra/blob/main/terraform/projects/nonprod-holos/shared_services/aws/github_oidc/main.tf#L90-L106
          role-to-assume: arn:aws:iam::271053619184:role/gha-app-role
          aws-region: us-east-2
          output-credentials: true
      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push container image
        run: |
          echo '{"credHelpers":{"public.ecr.aws":"ecr-login","271053619184.dkr.ecr.us-east-2.amazonaws.com":"ecr-login"}}' > ~/.docker/config.json
          # Configure git credentials to access github private repositories.
          export GIT_USERNAME=actions
          export GIT_PASSWORD='${{ secrets.GITHUB_TOKEN }}'
          # Build and push
          /kaniko/executor --dockerfile=toolkit/Dockerfile \
            --context='${{ github.repositoryUrl }}#${{ needs.git.outputs.sha }}' \
            --destination=${{ steps.login-ecr.outputs.registry }}/holos-run/container-images/toolkit:latest \
            --push-retry 5 \
            --image-name-with-digest-file /workspace/image-digest.txt
          # Make this an artifact?
          cat /workspace/image-digest.txt
